name: Bug Report
description: File a bug/issue report
title: '[BUG]: <title>'
labels: [Bug, Need Triage]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the problem
      description: |
        Describe how others can reproduce the problem

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
      attributes:
        label: What is the expected behaviour?
        description: |
          What is the expected behavior? What exactly should happen?
        placeholder: Tell us what you expect!
      validations:
        required: true
  - type: textarea
      attributes:
        label: What is observed behaviour?
        description: |
          How is the behavior current? What is different and what does it differ from?
        placeholder: Tell us what you see!
      validations:
        required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
      attributes:
        label: Anything else?
        description: |
          Links? References? Anything that will give us more context about the issue you are encountering!

          Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
      validations:
        required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true